import { describe } from "vitest";
import { shogitterDB } from "../src";

describe("shogitterDB", function () {
  describe("getAllRules", () => {
    it("has all values", () => {
      expect(shogitterDB.getAllRules().map((i) => i._id)).toHaveLength(114);
    });
  });
  describe("getRuleGenre", function () {
    it("matches snapshot", () => {
      expect(shogitterDB.getRuleGenre()).toMatchInlineSnapshot(`
              {
                "世界の将棋": [
                  76,
                  99,
                  100,
                  101,
                  102,
                ],
                "初形変則": [
                  17,
                  19,
                  27,
                  32,
                  39,
                  44,
                  45,
                  46,
                  47,
                  51,
                  52,
                  65,
                  79,
                  90,
                  91,
                  92,
                  96,
                  97,
                  98,
                  103,
                  104,
                  109,
                  110,
                ],
                "副作用系変則": [
                  18,
                  23,
                  36,
                  42,
                  69,
                  73,
                  77,
                  78,
                  106,
                  111,
                ],
                "動き系変則": [
                  26,
                  28,
                  29,
                  33,
                  34,
                  37,
                  38,
                  40,
                  41,
                  55,
                  56,
                  62,
                  67,
                  68,
                  70,
                  71,
                  72,
                  74,
                  86,
                  87,
                  88,
                  94,
                  95,
                  107,
                  112,
                  113,
                ],
                "古将棋": [
                  12,
                  13,
                  14,
                  15,
                  16,
                  43,
                  48,
                  49,
                  50,
                  59,
                  60,
                  61,
                  63,
                  64,
                ],
                "将棋以外": [
                  39,
                  80,
                  81,
                  82,
                  83,
                  84,
                  85,
                  89,
                  105,
                ],
                "持ち駒手番系変則": [
                  24,
                  25,
                  35,
                  53,
                  54,
                  57,
                  66,
                  75,
                  93,
                ],
                "新駒系変則": [
                  20,
                  21,
                  22,
                  30,
                  31,
                  58,
                  108,
                ],
                "本将棋": [
                  0,
                  1,
                  2,
                  3,
                  4,
                  5,
                  6,
                  7,
                  8,
                  9,
                  10,
                  11,
                ],
              }
            `);
    });
  });
});
